In [2]:
import numpy as np

### first question

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([[10,20,30],[40,50,60]])
result = arr1+arr2
result

array([[11, 22, 33],
       [41, 52, 63]])

### second question






In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([10,20])
arr2_reshaped = arr2.reshape(-1,1)
result = arr1*arr2_reshaped
result

array([[10, 20],
       [60, 80]])

In [5]:
arr = np.arange(1, 25).reshape(2, 3, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [6]:
arr[1,:,:]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [7]:
arr[:,:,-1]

array([[ 4,  8, 12],
       [16, 20, 24]])

In [8]:
arr_reversed = arr[::-1,:,:]
arr_reversed

array([[[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [9]:
arr_odd = arr.copy()
arr_odd[arr%2==0] = -1
arr_odd

array([[[ 1, -1,  3, -1],
        [ 5, -1,  7, -1],
        [ 9, -1, 11, -1]],

       [[13, -1, 15, -1],
        [17, -1, 19, -1],
        [21, -1, 23, -1]]])

In [10]:
arr3 = np.array([1,2,3,4,5,6])
arr_repeated = np.repeat(arr3[arr3%2 == 1],2)
arr_repeated

array([1, 1, 3, 3, 5, 5])

In [11]:
arr_repeat_basedon_values = np.repeat(arr3,arr3)
arr_repeat_basedon_values

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6])

In [12]:
arr4 = np.array([10,20,30])
normalized_arr = (arr4-arr4.min())/(arr4.max()-arr4.min())
normalized_arr

array([0. , 0.5, 1. ])

In [13]:
i = np.arange(3).reshape(3,1)
j = np.arange(3)
matrix = i*j
matrix

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [14]:
matrix = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12], 
                   [13, 14, 15, 16]])
np.fill_diagonal(matrix, 0)
print(matrix)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
